### ISSUE TITLE
authenticatedSubmitJob is not working

### ISSUE THREAD

**Issue by fdabrandao** [NEOS-Server/Kestrel-AMPL-Linux#2]
Hi,

While I was implementing a kestrel client with the same functionalities as this one, I noticed that the RPC method `authenticatedSubmitJob` does not seem to be working anymore.

```ampl
ampl: model diet.mod;
ampl: data diet.dat;
ampl: option solver kestrel;
ampl: option email "***";
ampl: option kestrel_options "solver=cplex";
ampl: solve;
Connecting to: neos-server.org:3333
Job 11019021 submitted to NEOS, password='ykHTALvF'
Check the following URL for progress report :
https://neos-server.org/neos/cgi-bin/nph-neos-solver.cgi?admin=results&jobnumber=11019021&pass=ykHTALvF
Job 11019021 dispatched
password: ykHTALvF
---------- Begin Solver Output -----------
Condor submit: 'neos.submit'
Condor submit: 'watchdog.submit'
Job submitted to NEOS HTCondor pool.
CPLEX 20.1.0.0: optimal solution; objective 88.2
1 dual simplex iterations (0 in phase I)
ampl: option neos_username "***";
ampl: option neos_user_password "***";
ampl: solve;
Connecting to: neos-server.org:3333
Traceback (most recent call last):
  File "/Users/fdabrandao/bin/ampl.macosx64/kestrel", line 76, in <module>
    (jobNumber, password) = kestrel.submit(xml)
  File "/Users/fdabrandao/bin/ampl.macos64/kestrelAMPL.py", line 75, in submit
    xml, self.username, self.userpassword, "kestrel")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<class 'Exception'>:POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.">
exit value 1
<BREAK>
```

The error `<class 'Exception'>:POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.` may be server side as I get exactly the same error in another language. 

BTW, in kestrelAMPL.submit: https://github.com/NEOS-Server/Kestrel-AMPL-Linux/blob/80ba94aa23130d4be6d5ce0766d378a17aedb969/kestrelAMPL.py#L71-L75 you have an extra argument "kestrel" for `submitJob` and `authenticatedSubmitJob` that does not seem to be necessary according to https://neos-server.org/neos/xml-rpc.html, but it fails in the same way even without this last argument.

**Comment by gnowzil** [comment]
There was an issue on the authentication side on the NEOS server.  This should be fix now.  Let me know if it still doesn't work.

**Comment by gnowzil** [comment]
Also the extra argument is optional.  It tells NEOS what interface is calling it.  So passing "kestrel" isn't necessary, but it does help us keep track of how people are using NEOS.

**Comment by fdabrandao** [comment]
Thank you for fixing this! It is working fine now.
